import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Header from '../components/Header/Header'
import Information from '../components/Information/information'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Multiclinica Fortaleza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <Header withBackground={true} />
      <main >
      <Information />
      </main>
      <Footer />
     
    </div>
  )
}
